### Get /

GET  http://localhost:3000/api/books/

### Get /

GET  http://localhost:3000/api/books/2/

### Post /

POST  http://localhost:3000/api/books/
Content-Type: application/json

{
  "name": "book 4"
}

###

PUT  http://localhost:3000/api/books/1/
Content-Type: application/json

{
    "name": "ny bok5"
}

###

DELETE   http://localhost:3000/api/books/1/
Content-Type: application/json
